README.md

This adds a pointer to the deploy directory from the top-level README to make the instructions for installing GCS more discoverable.

Add pointer to deploy directory

---

deploy/tasks/add-devices-to-peer.yml
deploy/templates/gcs-manifests/gcs-gd2.yml.j2

Fixes: #18 
output:
```
[vagrant@kube1 ~]$ kubectl get po -n gcs
NAME                                   READY   STATUS    RESTARTS   AGE
csi-attacher-glusterfsplugin-0         2/2     Running   0          28m
csi-nodeplugin-glusterfsplugin-99m5w   2/2     Running   0          28m
csi-nodeplugin-glusterfsplugin-jm768   2/2     Running   0          28m
csi-nodeplugin-glusterfsplugin-x9m5m   2/2     Running   0          28m
csi-provisioner-glusterfsplugin-0      2/2     Running   0          28m
etcd-5ntqcq5587                        1/1     Running   0          30m
etcd-nffhbtvq6h                        1/1     Running   0          31m
etcd-operator-7cb5bd459b-jnfv7         1/1     Running   0          32m
etcd-xrntbxh5xz …
```

add gluster as pod name prefix

---

deploy/README.md
deploy/deploy-k8s.yml
deploy/templates/gcs-manifests/gcs-csi.yml.j2

updated node plugin template which is required for kubernetes v1.12.1.
output
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:36:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```
```
[vagrant@kube1 ~]$ kubectl get po
NAME          READY   STATUS    RESTARTS   AGE
gcs-example   1/1     Running   0          45s
```
```
[vagrant@kube1 …
```

update kubernetes version to v1.12.1

---

deploy/templates/gcs-manifests/gcs-gd2.yml.j2

volume size
```
root@gcs-example:/data# df -h /data
Filesystem                                                              Size  Used Avail Use% Mounted on
gluster-kube1-0.glusterd2.gcs:pvc-64c5e59e-d83d-11e8-833c-5254001fb83f 1014M   43M  972M   5% /data
```
Rest response
```
curl http://gluster-kube1-0.glusterd2.gcs:24007/v1/volumes/pvc-64c5e59e-d83d-11e8-833c-5254001fb83f/status |python -m json.tool
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  1580  100  1580    0     0   9272      0 --:--:-- --:--:-- --:--:--  9294
{
"info": {
"distribute-count": 1,
"id": "0d2c6927-b42f-488a-a1f1-8ebb59b97f1f",
"metadata": {
"VolumeOwner": "org.gluster.glusterfs"
},
"name": "pvc-64c5e59e-d83d-11e8-833c-5254001fb83f", …
```

Update gd2 container image to fix size issue

---

deploy/Vagrantfile
deploy/deploy-gcs.yml
deploy/group_vars/all.yml
deploy/templates/gcs-manifests/gcs-gd2-services.yml.j2
deploy/templates/gcs-manifests/gcs-grafana.yml.j2
deploy/templates/gcs-manifests/gcs-prometheus-alertmanager-cluster.yml.j2
deploy/templates/gcs-manifests/gcs-prometheus-bundle.yml.j2
deploy/templates/gcs-manifests/gcs-prometheus-operator.yml.j2
deploy/templates/gcs-manifests/monitoring-namespace.yml.j2

Connects to gluster/gluster-prometheus#45 . This PR integrates Prometheus deployment with the GCS setup. Prometheus is a monitoring system used for scraping metrics that are exposed from exporters. With the PR [gluster/glusterd2#1308](https://github.com/gluster/glusterd2/pull/1308/), gluster-prometheus exporter will be containerized along with glusterd2. 
Since monitoring systems are not stateless i.e stateful, they are difficult to set up in a kubernetes environment. The workaround is the prometheus operator. The operator takes care of deploying and managing the prometheus server and also managing a set of Custom Resource Definition (CRD) objects called ServiceMonitor, Prometheus, Alertmanager, PrometheusRule. To learn more about these CRDs, refer …

GCS-Prometheus Integration

---

deploy/README.md
deploy/templates/gcs-manifests/gcs-prometheus-bundle.yml.j2

The prometheus server brought up by the Operator exposes the port ```9090``` with the port name ```web```.  In our deployment, the targetPort specified in the NodePort service(which exposes the metrics outside) is supposed to point to the port exposed by the prometheus server and hence should be changed from ```targetPort: metrics```. Deleting that line will do the trick as ```port: 9090``` and no targetPort specified will default to ```targetPort: 9090``` as well.

Add Instructions on how to view the metrics and also fix NodePort service that exposes the metrics

---

deploy/README.md

In PR #43 support for `GD2_ENDPOINTS` env variable has been added. we don't
need to pass `--endpoints` option to the glustercli to talk to glusterd2.

update Readme to access gluster-cli

---

deploy/deploy-gcs.yml
deploy/tasks/add-devices-to-peer.yml

Deployment tended to fail at 2 points:
- When getting the gd2 peers
- When adding devices
It appears that these two failure points can be avoided by adding
retries. This commit adds those retries. We retry getting peers by just
removing the (repeat) fetch of the peers as the first instance had
retries already. When adding devices, we simply try again if necessary
during the loop.
The fixes (particularly the second) are not ideal as I don't think we
have a full understanding of the nature of the transient failures.
-----
I believe this will help #44  and #38, but I'm not closing them since it's unclear that this is the proper fix, particularly the retry during device add.

Add retries to deployment

---

deploy/Vagrantfile
deploy/deploy-gcs.yml

The Prometheus objects deployment fails sometimes because there is a race in Kubernetes that the CRD creation finished but the API is not actually available. The problem is fixed by ignoring the error, waiting for the CRDs to get registered, waiting for the Service monitor resource to be ready and then re-deploying the Prometheus objects again.
Fixes #67

Fix Prometheus CRD deployment issue and changed VagrantFile to forward port from one Node

---

deploy/Vagrantfile

Hopefully, will make deployment slightly faster.
(Most of the inefficiencies are in Kubespray, will file issues
separately)

Improvements to the libvirt provider definitions in the Vagrantfile

---

deploy/templates/gcs-manifests/gcs-csi.yml.j2

This gives more descriptive logs and helps us to debug the issue in `gluster-csi driver`
sample logs
```
I1205 06:44:01.017751       1 utils.go:102] GRPC response: capabilities:<rpc:<type:CREATE_DELETE_VOLUME > > capabilities:<rpc:<type:LIST_VOLUMES > > capabilities:<rpc:<type:CREATE_DELETE_SNAPSHOT > > capabilities:<rpc:<type:LIST_SNAPSHOTS > > 
I1205 06:44:01.019166       1 utils.go:96] GRPC call: /csi.v0.Identity/GetPluginInfo
I1205 06:44:01.019188       1 utils.go:97] GRPC request: 
I1205 06:44:01.019507       1 identityserver.go:21] plugininfo response: name:"org.gluster.glusterfs" vendor_version:"0.0.9" 
I1205 06:44:01.019550       1 utils.go:102] GRPC response: name:"org.gluster.glusterfs" vendor_version:"0.0.9" 
I1205 …
```

add log level to the gluster-csi-driver containers in deployment file

---

deploy/deploy-gcs.yml
deploy/templates/gcs-manifests/gcs-operator-crd.yml.j2
deploy/templates/gcs-manifests/gcs-operator.yml.j2

This will deploy the latest version of the operator along with the rest of GCS. Currently, the operator doesn't do anything useful. As it handles more of the deployment, we can trim down the rest of the `deploy-gcs.yml` playbook.
Fixes #87

Add deployment of Anthill to GCS

---

deploy/templates/gcs-manifests/gcs-operator.yml.j2

The Role & RoleBinding were being created in the "default" namespace
instead of the "gcs" namespace. The result was that Anthill was unable
to query the running pods due to insufficient permissions of its service
account. As a result, the Anthill pod was in CrashLoop. This adds the
proper namespace tags to put the Role/RoleBinding into the gcs namespace
giving the operator's service account appropriate permissions.

Add anthill role to correct (gcs) namespace

---

deploy/templates/gcs-manifests/gcs-csi.yml.j2

Default timeout in rest client is 30s, having 30 sec
of timeout is not enough to communicate
with glusterd2, so providing a new configuration
to set the rest client timeout.
Merge this ones https://github.com/gluster/gluster-csi-driver/pull/137 is merged

Add timeout option in gluster-csi-driver

---

deploy/deploy-k8s.yml
deploy/vagrant-playbook.yml

... instead of in deploy-k8s.yml, allowing it to be used outside the
vagrant environment. Any specific customization needed in the vagrant
environment needs to be done in vagrant-playbook.yml.

Install socat in vagrant-playbook.yml

---

deploy/templates/gcs-manifests/gcs-csi.yml.j2

driver-registrar is deprecated and replaced with
cluster-driver-registrar and node-driver-registrar

update side car containers to latest stable version

---

README.md

This will add gluster-mixins section to the gcs README. 
reference: https://github.com/gluster/gcs/pull/109

Added gluster-mixins section to gcs README

---

deploy/templates/gcs-manifests/gcs-csi.yml.j2

The gluster file-based CSI driver is now built as `gluster/glusterfs-csi-driver` in Quay and Docker Hub. This commit moves from the now deprecated gluster-csi-driver to the new name.
Requires gluster/gluster-csi-driver#159

Switch gluster CSI driver container image

---

deploy/templates/gcs-manifests/gcs-gd2.yml.j2

Add devices phase in gcs setup was hung with following error in gd2 container.
" WARNING: Device /dev/vda not initialized in udev database even after waiting 10000000 microseconds."
All pv commands (e.g. pvdisplay, pvcreate..) takes lot of time causing the failure of gcs setup.
It's found out that exporting /run/udev solves the issue. 
Signed-off-by: Kotresh HR <khiremat@redhat.com>
------
Fixes #129

Make /run/udev available to gd2 container from host

---

deploy/templates/gcs-manifests/gcs-virtblock-csi.yml.j2

glustervirtblock-nodeplugin mounts the virtual block
which has to create devices at /dev. Without /dev
bind mounted, device creation fails.
Signed-off-by: Kotresh HR <khiremat@redhat.com>

Make /dev available to glustervirtblock-nodeplugin

---

doc/installation.md
doc/quick-start-guide.md
pages/005-ease-of-use.md

kubectl plugins are supported from `v1.13`
https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/
Converted `glustercsctl` tool into kubectl plugin. Updated the doc pages
for the same.
Signed-off-by: Aravinda VK <avishwan@redhat.com>

Changed `glustercsctl` tool as kubectl plugin

---

deploy/templates/gcs-manifests/gcs-gd2.yml.j2

If kube cluster nodes uses FQDN as hostname,
GD2 pods fails to come up. The patch fixes the same.
Signed-off-by: Kotresh HR <khiremat@redhat.com>

Fix GD2 pods failure #148
